author: C Bouton
database: false
description: 'Allows for spoutcraft players to receive coordinates like they had pressed
  F3. '
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.cbouton.plugins.spoutcoords.Spoutcoords
name: SpoutCoords
website: cbouton.com
startup: postworld
version: 0.6.1
depend: [Spout]
permissions:
  SpoutCoords.Coords:
    default: true
    description: Allows use of F4 coordinates.
  SpoutCoords.Mobs:
    default: op
    description: Easter Egg.

